### PR TITLE
feat: add ts types with aegir

### PR DESCRIPTION
**Pull request by hugomrdias**
this is a best effort approach since multiformats/multiformats will probably superseed this repo soon.

### CODE REVIEW

**Review by vmx — CHANGES_REQUESTED** [review]
Can you please remove the unrelated things like adding a GitHub issue template from this PR?

It also removes the `withIs`, which is a (potentially) huge breaking change. I'd prefer if we keep that in for compatibility. I don't think it makes sense to remove it as it will be replaced by multiformats/cid anyway.

**Comment by Gozala** [comment]
> It also removes the `withIs`, which is a (potentially) huge breaking change. I'd prefer if we keep that in for compatibility. I don't think it makes sense to remove it as it will be replaced by multiformats/cid anyway.

@vmx `withIs` unfortunately triggers various different bugs in TS & I'm guessing that is also why it end up been part of this PR. Switch to `multiformats/cid` might be larger effort but probably worth considering. I'd be interested in helping with that effort.

**Comment by hugomrdias** [comment]
@vmx im just trying to keep these repos consistent with each other and has you said we might move to the new multiformats soon, so theres no point in spending too much time in this and thats why i just added everything in.

**Comment by vmx** [comment]
@Gozala @achingbrain @hugomrdias So we do a new major release of js-cid for adding TypeScript types? If there's agreement that's fine with me.

@hugomrdias Though next time I'd prefer having things like adding issue templates in a separate commit as it's totally unrelated.

**Comment by hugomrdias** [comment]
@vmx nothing is actually a breaking change it behaves exactly as before, just a little bit safer now

**Comment by vmx** [comment]
@Gozala @achingbrain @hugomrdias: oh sorry I missed that line: https://github.com/multiformats/js-cid/pull/131/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R17

Which add the symbol which `withIs()` is adding. So it's not a breaking change.

**Comment by vmx** [comment]
I've removed the issue templates, I don't want them in this repo, I think it increases the burden of reporting a bug without having too much benefit (we also don't get that many bug reports here).

**Review by vmx — APPROVED** [review]
Thanks for the change and also updating the CI to GitHub actions (I should've done that a long time ago myself).

**Pull request merged**
